matrix:
  include:
    - os: osx
      osx_image: xcode9.3
script:
  - cd URITemplate && swift package generate-xcodeproj && cd ..
  - xcodebuild -project Mockingjay.xcodeproj -scheme Mockingjay test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - pod lib lint --quick
